version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Add this if you have a backend service in the same docker-compose file
    # depends_on:
    #   - backend
